config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "boards#index"

  get '/boards/:id', to: 'boards#show', as: 'board'
  get '/cards/:id', to: 'cards#show', as: 'card'
  get '/trello', to: 'trello_settings#index', as: 'trello_settings'
  post '/trello', to: 'trello_settings#update', as: 'update_trello_settings'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :verify_trello_api_secrets
  skip_before_action :verify_authenticity_token

  private

  def verify_trello_api_secrets
    redirect_to trello_settings_path unless has_all_trello_secrets?
    configure_trello
  end

  def configure_trello
    Trello.configure do |config|
      config.developer_public_key = session[:app_key]
      config.member_token = session[:api_key]
    end
  end

  def has_all_trello_secrets?
    session[:app_key].present? && session[:api_key].present?
  end
end

app/controllers/boards_controller.rb
# frozen_string_literal: true

class BoardsController < ApplicationController
  def index
    @user = Trello::Member.find(:me)
    @boards = @user.boards
  end
  
  def show
    @board = BpmTrello::Models::Board.new(Trello::Board.find(board_id))
  end

  private

  def board_id
    permitted_params[:id]
  end

  def permitted_params
    params.permit(:id)
  end
end

app/controllers/cards_controller.rb
# frozen_string_literal: true

class CardsController < ApplicationController
  def show
    trello_card = Trello::Card.find(card_id)
    @card = BpmTrello::Models::Card.new(trello_card)

    @preprocessed_card = BpmTrello::Preprocessor.preprocess(trello_card)
    @final_text = BpmTrello::BpmInfoExtractor.extract_from(@preprocessed_card)
  end

  private

  def card_id
    permitted_params[:id]
  end

  def permitted_params
    params.permit(:id)
  end
end

app/controllers/trello_settings_controller.rb
class TrelloSettingsController < ApplicationController
  skip_before_action :verify_trello_api_secrets
  def index; end

  def update
    session[:app_key] = trello_params[:app_key]
    session[:api_key] = trello_params[:api_key]

    configure_trello

    redirect_to root_path
  end

  private

  def trello_params
    params.permit(:app_key, :api_key)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trello_settings_helper.rb
module TrelloSettingsHelper
end

app/views/boards/index.html.erb
<h2>Hello, <%= @user.full_name %></h2>
<h5>These are all the boards we could find in your Trello account. Click one of them to see its cards.</h5>
<div class="BoardGrid">
  <% @boards.each do |board| %>
    <%= link_to board_path(id: board.id), class: "BoardCard", style: "background-color: #{board.prefs["backgroundColor"]}" do %>
      <div>
        <%= board.name %>
      </div>  
    <% end %>
  <% end %>
</div>

app/views/boards/show.html.erb
<h2>Board: <%= @board.name %></h1>
<h5>These are all cards we found in this board. There might be a lot of them so you should try searching for its name by pessing <code>Ctrl + F</code> and opening the browser page search.
Once you have found the card you're looking for, click in "EXTRACT" to generate its business process description.</h5>
<small>
  Generating the business process description for a card might take a while, up to several minutes! Please wait patiently after clicking to extract a card. You might even get yourself a cup of coffee or watch a short youtube video.
</small>

<div class="CardGrid">
<% @board.cards.each do |card| %>
  <div class="card">
    <div class="card-content">
      <span class="card-title"><%= card.name %></span>
    </div>
    <div class="card-action">
      <%= link_to "extract", card_path(id: card.id) %>
    </div>
  </div>
<% end %>
</div>

app/views/cards/show.html.erb
<h1>Card: <%= @card.name %></h1>

<div class="CardExtractionGrid">
  <div class="card">
    <div class="card-content">
      <span class="card-title">Original card</span>
      <h5> <%= @card.name %> </h5>
      <b>Description</b>
      <div>
        <%= @card.desc %>
      </div>

      <b>Checklists</b>
      <div>
      <% @card.checklists.map do |checklist| %>
        <ul>
          <% checklist.items.map do |item| %>
          <li>
          - <%= item.name %>
          </li>
          <% end %>
        </ul>
        <% end %>
      </div>
      
      <b>Comments</b>
      <div>
        <%= @card.comments_as_conversation %>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-content">
      <span class="card-title">Preprocessed card</span>
      <h5> <%= @preprocessed_card.name %> </h5>
      <b>Description</b>
      <div>
        <%= @preprocessed_card.desc %>
      </div>

      <b>Checklists</b>
      <div>
        <% @preprocessed_card.checklists.map do |checklist| %>
        <ul>
          <% checklist.items.map do |item| %>
          <li>
          - <%= item.name %>
          </li>
          <% end %>
        </ul>
        <% end %>
      </div>
      
      <b>Comments</b>
      <div>
        <%= @preprocessed_card.comments_as_conversation %>
      </div>
    </div>    
  </div>

  <div class="CardActivitiesCard">
    <h4>Final text</h4>
    <%= @final_text %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BpmTrello</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="#" style="margin-left: 30px;" class="brand-logo">BPM Trello</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a target="_blank" href="http://github.com/guitassinari">Developed by Guilherme Tassinari</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/trello_settings/index.html.erb
<div style="height: 100%;" class="valign-wrapper">
  <div class="card">
    <div class="card-content">
      <span class="card-title">API Keys</span>
      <p>
        Please provide a Trello API Key and Token. You can find out how to generate those in the <a target="_blank" href="https://developer.atlassian.com/cloud/trello/guides/rest-api/api-introduction/#authentication-and-authorization">Trello API Introduction</a>.
        This is going to allow BPM Trello to access your Trello data and perform the business process description generation.
      </p>
      <small>
       Don't worry! Neither these keys nor any of your data are not stored in any kind of server database and only lives during this session.
      </small>
      <%= form_with(url: update_trello_settings_path) do |f| %>
        <div>
          <%= label_tag(:app_key, "APP KEY") %>
          <%= f.text_field :app_key %>
        </div>
        <div>
          <%= label_tag(:api_key, "API KEY") %>
          <%= f.text_field :api_key %>
        </div>
        <button class="btn waves-effect waves-light" type="submit" name="action">
          Submit
          <i class="material-icons right">send</i>
        </button>
      <% end %>
    </div>
  </div>
</div>